//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewSheets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewSheets.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a bookmark to.
        /// </summary>
        internal static string AddingBookmark {
            get {
                return ResourceManager.GetString("AddingBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with bookmarks.
        /// </summary>
        internal static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed &apos;SaveTo ViewSheets&apos; settings..
        /// </summary>
        internal static string ChangedViewSheetSettings {
            get {
                return ResourceManager.GetString("ChangedViewSheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the system&apos;s dialog and have you change some settings..
        /// </summary>
        internal static string ChangeViewSheetSettings {
            get {
                return ResourceManager.GetString("ChangeViewSheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change some settings via this NET-Hook. ALL OFF, except for WCS, Color and ZDepth..
        /// </summary>
        internal static string ChangingViewSheetSettings {
            get {
                return ResourceManager.GetString("ChangingViewSheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the main sheet..
        /// </summary>
        internal static string CouldNotFindSheet {
            get {
                return ResourceManager.GetString("CouldNotFindSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating 3 view sheets, first is a system assigned view sheet name, the second is our custom view sheet name..
        /// </summary>
        internal static string CreateViewSheets {
            get {
                return ResourceManager.GetString("CreateViewSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;ll cycle through all of the view sheets making each the active view sheet..
        /// </summary>
        internal static string CycleActiveSheetMessage {
            get {
                return ResourceManager.GetString("CycleActiveSheetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sheet demo is complete.
        /// </summary>
        internal static string DemoCompleted {
            get {
                return ResourceManager.GetString("DemoCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sheet demo ended with failure(s)..
        /// </summary>
        internal static string DemoFailed {
            get {
                return ResourceManager.GetString("DemoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying view sheet data.
        /// </summary>
        internal static string DisplayViewSheetData {
            get {
                return ResourceManager.GetString("DisplayViewSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sheets are not enabled, so we will enable them.&quot;.
        /// </summary>
        internal static string EnableViewSheets {
            get {
                return ResourceManager.GetString("EnableViewSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new view sheet.
        /// </summary>
        internal static string FailedCreateViewSheet {
            get {
                return ResourceManager.GetString("FailedCreateViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change settings..
        /// </summary>
        internal static string FailedToChangeSettings {
            get {
                return ResourceManager.GetString("FailedToChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a bookmark .
        /// </summary>
        internal static string FailedToCreateViewSheetBookmark {
            get {
                return ResourceManager.GetString("FailedToCreateViewSheetBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete view sheet bookmark.
        /// </summary>
        internal static string FailedToDeleteBookmark {
            get {
                return ResourceManager.GetString("FailedToDeleteBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete view sheet.
        /// </summary>
        internal static string FailedToDeleteViewSheet {
            get {
                return ResourceManager.GetString("FailedToDeleteViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the active view sheet.
        /// </summary>
        internal static string FailedToFindActiveViewSheet {
            get {
                return ResourceManager.GetString("FailedToFindActiveViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the name of the active view sheet.
        /// </summary>
        internal static string FailedToFindNameOfActiveViewSheet {
            get {
                return ResourceManager.GetString("FailedToFindNameOfActiveViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve view sheets settings..
        /// </summary>
        internal static string FailedToGetSaveToViewSheetSettings {
            get {
                return ResourceManager.GetString("FailedToGetSaveToViewSheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get sheet data..
        /// </summary>
        internal static string FailedToGetSheetData {
            get {
                return ResourceManager.GetString("FailedToGetSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save bookmark..
        /// </summary>
        internal static string FailedToSaveBookmark {
            get {
                return ResourceManager.GetString("FailedToSaveBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the name of the active view sheet.
        /// </summary>
        internal static string FailedToSetActiveViewSheet {
            get {
                return ResourceManager.GetString("FailedToSetActiveViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set view sheet at index zero as the active view sheet.
        /// </summary>
        internal static string FailedToSetActiveViewSheetAtIndexZero {
            get {
                return ResourceManager.GetString("FailedToSetActiveViewSheetAtIndexZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;ll change some settings via this NET-Hook..
        /// </summary>
        internal static string NowWeWillChangeSettings {
            get {
                return ResourceManager.GetString("NowWeWillChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the &apos;SaveTo ViewSheets&apos; settings..
        /// </summary>
        internal static string SaveToViewSheetsSettings {
            get {
                return ResourceManager.GetString("SaveToViewSheetsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting view sheet at index zero as the active view sheet.
        /// </summary>
        internal static string SetActiveViewSheetAtIndexZero {
            get {
                return ResourceManager.GetString("SetActiveViewSheetAtIndexZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting our custom view sheet as the active view sheet.
        /// </summary>
        internal static string SetOurCustomSheetAsTheActiveViewSheet {
            get {
                return ResourceManager.GetString("SetOurCustomSheetAsTheActiveViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the changed &apos;SaveTo ViewSheets&apos; settings..
        /// </summary>
        internal static string ShowChangedSettings {
            get {
                return ResourceManager.GetString("ShowChangedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;ll display the &apos;SaveTo ViewSheets&apos; settings..
        /// </summary>
        internal static string ShowSaveToSettings {
            get {
                return ResourceManager.GetString("ShowSaveToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;ll display the system&apos;s dialog and have you change some settings.
        /// </summary>
        internal static string ShowSettingsDialog {
            get {
                return ResourceManager.GetString("ShowSettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sheets Demo.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sheet created successfully.
        /// </summary>
        internal static string ViewSheetCreated {
            get {
                return ResourceManager.GetString("ViewSheetCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sheet name is invalid (it might already exist).
        /// </summary>
        internal static string ViewSheetNameInValid {
            get {
                return ResourceManager.GetString("ViewSheetNameInValid", resourceCulture);
            }
        }
    }
}
